import {
  EXECUTE,
  HKEY_CLASSES_ROOT,
  HKEY_CURRENT_CONFIG,
  HKEY_CURRENT_USER,
  HKEY_LOCAL_MACHINE,
  HKEY_PERFORMANCE_DATA,
  HKEY_USERS,
  Key,
  KeyInfo,
  RegistryBackend,
  Rights,
  Types,
} from "./types.mjs";
import { Registry, RegistryError, RegistryKey, isRegistryAvailable } from "./registry.mjs";
export {
  EXECUTE,
  HKEY_CLASSES_ROOT,
  HKEY_CURRENT_CONFIG,
  HKEY_CURRENT_USER,
  HKEY_LOCAL_MACHINE,
  HKEY_PERFORMANCE_DATA,
  HKEY_USERS,
  type Key,
  type KeyInfo,
  Registry,
  type RegistryBackend,
  RegistryError,
  RegistryKey,
  Rights,
  Types,
  isRegistryAvailable,
};
