packages:
  - std/*
  - os/*
  - ssh/*

allowBuilds:
  koffi: set this to true or false

catalog:
  "vite-plus": "0.1.24"
  "@types/node": "^25.9.3"
  "@types/bun": "^1.3.14"
  "@typescript/native-preview": "7.0.0-dev.20260509.2"
  "bumpp": "^11.1.0"
  "typescript": "^6.0.3"
