import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vite-plus";

const dir = join(import.meta.dirname, "..", "..");
const runner = join(dir, "eng", "scripts", "node-test-runner.mjs");
const nodeTestShim = fileURLToPath(new URL("../../eng/scripts/node-test-shim.ts", import.meta.url));

export default defineConfig({
  pack: {
    dts: {
      tsgo: true,
    },
    entry: [
      "./src/basename.ts",
      "./src/common.ts",
      "./src/common/assert-path.ts",
      "./src/common/basename.ts",
      "./src/common/common.ts",
      "./src/common/constants.ts",
      "./src/common/dirname.ts",
      "./src/common/format.ts",
      "./src/common/from-file-url.ts",
      "./src/common/glob-to-reg-exp.ts",
      "./src/common/normalize-string.ts",
      "./src/common/normalize.ts",
      "./src/common/relative.ts",
      "./src/common/strip-trailing-separators.ts",
      "./src/common/to-file-url.ts",
      "./src/constants.ts",
      "./src/dirname.ts",
      "./src/extname.ts",
      "./src/format.ts",
      "./src/from-file-url.ts",
      "./src/glob-to-regexp.ts",
      "./src/globals.ts",
      "./src/index.ts",
      "./src/is-absolute.ts",
      "./src/is-glob.ts",
      "./src/join.ts",
      "./src/join-globs.ts",
      "./src/normalize.ts",
      "./src/normalize-glob.ts",
      "./src/parse.ts",
      "./src/posix/basename.ts",
      "./src/posix/common.ts",
      "./src/posix/constants.ts",
      "./src/posix/dirname.ts",
      "./src/posix/extname.ts",
      "./src/posix/format.ts",
      "./src/posix/from-file-url.ts",
      "./src/posix/glob-to-regexp.ts",
      "./src/posix/index.ts",
      "./src/posix/is-absolute.ts",
      "./src/posix/is-glob.ts",
      "./src/posix/join.ts",
      "./src/posix/join-globs.ts",
      "./src/posix/normalize.ts",
      "./src/posix/normalize-glob.ts",
      "./src/posix/parse.ts",
      "./src/posix/relative.ts",
      "./src/posix/resolve.ts",
      "./src/posix/to-file-url.ts",
      "./src/posix/to-namespaced-path.ts",
      "./src/posix/util.ts",
      "./src/relative.ts",
      "./src/resolve.ts",
      "./src/os.ts",
      "./src/to-file-url.ts",
      "./src/to-namespaced-path.ts",
      "./src/types.ts",
      "./src/windows/basename.ts",
      "./src/windows/common.ts",
      "./src/windows/constants.ts",
      "./src/windows/dirname.ts",
      "./src/windows/extname.ts",
      "./src/windows/format.ts",
      "./src/windows/from-file-url.ts",
      "./src/windows/glob-to-regexp.ts",
      "./src/windows/index.ts",
      "./src/windows/is-absolute.ts",
      "./src/windows/is-glob.ts",
      "./src/windows/join.ts",
      "./src/windows/join-globs.ts",
      "./src/windows/normalize.ts",
      "./src/windows/normalize-glob.ts",
      "./src/windows/parse.ts",
      "./src/windows/relative.ts",
      "./src/windows/resolve.ts",
      "./src/windows/to-file-url.ts",
      "./src/windows/to-namespaced-path.ts",
      "./src/windows/util.ts",
    ],
    exports: {
      exclude: [
        "./common/assert-path",
        "./common/basename",
        "./common/common",
        "./common/constants",
        "./common/dirname",
        "./common/format",
        "./common/from-file-url",
        "./common/glob-to-reg-exp",
        "./common/normalize-string",
        "./common/normalize",
        "./common/relative",
        "./common/strip-trailing-separators",
        "./common/to-file-url",
        "globals",
        "os",
        "posix/util",
        "windows/util",
      ],
    },
    outDir: "esm",
    platform: "node",
  },
  test: {
    runner,
  },
  resolve: {
    alias: {
      "node:test": nodeTestShim,
    },
  },
});
