import {
  DomainInfo,
  MachineRole,
  OsRelease,
  OsReleaseLike,
  OsVersionInfo,
  ProductEdition,
  ProductType,
  SuiteMask,
  WinReleaseBackend,
} from "./types.mjs";
import {
  getWindowsDomainInfo,
  getWindowsOsRelease,
  getWindowsOsReleaseJson,
  getWindowsOsReleaseText,
  getWindowsProductEdition,
  getWindowsVersion,
  isAvailable,
  isWindowsDomainController,
  isWindowsDomainJoined,
  isWindowsServer,
  isWindowsWorkstation,
} from "./os_release.mjs";
export {
  type DomainInfo,
  MachineRole,
  type OsRelease,
  type WinReleaseBackend as OsReleaseBackend,
  type OsReleaseLike,
  type OsVersionInfo,
  ProductEdition,
  ProductType,
  SuiteMask,
  getWindowsDomainInfo,
  getWindowsOsRelease,
  getWindowsOsReleaseJson,
  getWindowsOsReleaseText,
  getWindowsProductEdition,
  getWindowsVersion,
  isAvailable,
  isWindowsDomainController,
  isWindowsDomainJoined,
  isWindowsServer,
  isWindowsWorkstation,
};
